/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PROTO_READING_PB_H_INCLUDED
#define PB_PROTO_READING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Reading {
    float temperature;
    pb_callback_t unit;
    float humidity;
} Reading;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Reading_init_default                     {0, {{NULL}, NULL}, 0}
#define Reading_init_zero                        {0, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Reading_temperature_tag                  1
#define Reading_unit_tag                         2
#define Reading_humidity_tag                     3

/* Struct field encoding specification for nanopb */
#define Reading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       1) \
X(a, CALLBACK, SINGULAR, STRING,   unit,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          3)
#define Reading_CALLBACK pb_default_field_callback
#define Reading_DEFAULT NULL

extern const pb_msgdesc_t Reading_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Reading_fields &Reading_msg

/* Maximum encoded size of messages (where known) */
/* Reading_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
